1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [2]:
import numpy as np

In [3]:
iris= np.genfromtxt(r"C:\Users\udayk\Downloads\Iris_clean_-_Copy.csv",dtype= "float16",delimiter=",")
iris

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

### Sepal_length

In [4]:
sepal_length=iris[1:,0:1]  # accessing the sepallength column
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [5]:
sepal_length= np.where(sepal_length== -1,np.nan,sepal_length)  # missing values will be replaced by nan
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [6]:
med= np.nanmedian(sepal_length)
med

5.8

In [7]:
sepal_length= np.where(np.isnan(sepal_length),med,sepal_length) # nan will be replaced by median 
sepal_length

array([[  5.1],
       [  4.9],
       [  4.7],
       [  4.6],
       [ 50. ],
       [  5.4],
       [  4.6],
       [  5. ],
       [  4.4],
       [  4.9],
       [  5.4],
       [  4.8],
       [  4.8],
       [  4.3],
       [  5.8],
       [  5.7],
       [ 50.4],
       [  5.1],
       [  5.7],
       [  5.1],
       [  5.4],
       [  5.1],
       [  4.6],
       [  5.1],
       [  4.8],
       [  5. ],
       [  5. ],
       [  5.2],
       [  5.2],
       [  4.7],
       [  4.8],
       [  5.4],
       [  5.2],
       [  5.5],
       [  4.9],
       [  5. ],
       [  5.5],
       [  4.9],
       [  4.4],
       [  5.1],
       [  5. ],
       [  4.5],
       [  4.4],
       [  5. ],
       [  5.1],
       [  4.8],
       [  5.1],
       [  4.6],
       [  5.3],
       [  5. ],
       [  7. ],
       [  6.4],
       [  6.9],
       [  5.5],
       [  6.5],
       [  5.7],
       [116.3],
       [  4.9],
       [  6.6],
       [  5.2],
       [  5. ],
       [  5.9],
       [

In [8]:
cond= (sepal_length>10)|(sepal_length<1)

In [90]:
sepal_length= np.where(cond,med,sepal_length).astype("int32")
sepal_length                                                 # outliers will be replaced by median

array([[5],
       [4],
       [4],
       [1],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [4],
       [1],
       [4],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [4],
       [5],
       [5],
       [5],
       [1],
       [4],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [5],
       [4],
       [5],
       [5],
       [7],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [4],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
    

**What is the mean value of sepal length**

In [91]:
np.mean(sepal_length)

5.303030303030303

**sort the sepal length in ascending order.**

In [11]:
np.sort(sepal_length)

array([[5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [4],
       [5],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [5],
       [4],
       [5],
       [5],
       [7],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [4],
       [6],
       [5],
       [5],
       [5],
       [6],
       [6],
       [5],
       [6],
       [5],
       [5],
       [6],
       [5],
       [5],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [6],
       [5],
       [5],
       [5],
       [5],
    

**apply all statistical measures on  sepal length**

In [12]:
np.mean(sepal_length)   #mean

5.387878787878788

In [13]:
np.median(sepal_length)   #median

5.0

In [14]:
Range= np.max(sepal_length)-np.min(sepal_length)     #Range
Range

3

In [15]:
np.var(sepal_length)   #Variance

0.6980348943985308

In [16]:
np.std(sepal_length)     #standard deviation

0.8354848259534884

#### IQR

In [17]:
q1= np.percentile(sepal_length,25)
q1

5.0

In [18]:
q3= np.percentile(sepal_length,75)
q3

6.0

In [19]:
IQR = q3-q1
IQR

1.0

In [20]:
lower_limit= q1-1.5*IQR
lower_limit

3.5

In [21]:
upper_limit= q3+1.5*IQR
upper_limit

7.5

In [22]:
sepal_length[sepal_length>upper_limit]

array([], dtype=int32)

In [23]:
sepal_length[sepal_length<lower_limit]

array([], dtype=int32)

### Sepal_width

In [24]:
sepal_width=iris[1:,1:2]  #accessing sepalwidth column
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  nan],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  nan],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  nan],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [25]:
sepal_width= np.where(sepal_width== -1,np.nan,sepal_width)   #replacing missing values with nan
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  nan],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  nan],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  nan],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [26]:
med= np.nanmedian(sepal_width)
med

3.0

In [27]:
sepal_width= np.where(np.isnan(sepal_width),med,sepal_width)  #replacing missing values with median
sepal_width

array([[  3.5],
       [  3. ],
       [  3.2],
       [  3.1],
       [  3.6],
       [  3. ],
       [  3.4],
       [  3.4],
       [  2.9],
       [  3.1],
       [  3.7],
       [  3.4],
       [130. ],
       [  3. ],
       [  4. ],
       [  4.4],
       [  3. ],
       [  3.5],
       [  3.8],
       [  3.8],
       [  3.4],
       [  3.7],
       [  3.6],
       [  3.3],
       [  3.4],
       [  3. ],
       [ 34. ],
       [  3.5],
       [  3.4],
       [  3.2],
       [  3.1],
       [  3.4],
       [  4.1],
       [  4.2],
       [  3.1],
       [  3.2],
       [  3.5],
       [  3.1],
       [  3. ],
       [  3.4],
       [  3.5],
       [  2.3],
       [  3.2],
       [  3.5],
       [  3.8],
       [  3. ],
       [  3.8],
       [  3.2],
       [  3.7],
       [  3.3],
       [  3.2],
       [  3.2],
       [  3. ],
       [  2.3],
       [  2.8],
       [  2.8],
       [  3.3],
       [  2.4],
       [  2.9],
       [  2.7],
       [  2. ],
       [  3. ],
       [

In [29]:
cond= (sepal_width>5)|(sepal_width<1)

In [92]:
sepal_width= np.where(cond,med,sepal_width).astype("int32") # type conversion
sepal_width                                                 # replacing outliers with median

array([[3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [2],
    

**sort the sepal width in ascending order.**

In [93]:
np.sort(sepal_width)

array([[3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [1],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [3],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [2],
       [3],
       [3],
       [2],
       [2],
       [2],
       [3],
       [2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [2],
       [2],
       [2],
       [2],
       [2],
    

**apply all statistical measures on sepal width**

In [94]:
np.mean(sepal_width)  #mean

2.587878787878788

In [95]:
np.median(sepal_width) #median

3.0

In [96]:
Range = np.max(sepal_width)-np.min(sepal_width)  #range
Range

3

In [97]:
np.var(sepal_width)  #range

0.339247015610652

In [98]:
np.std(sepal_width)    #standard deviation

0.5824491528113437

#### IQR

In [99]:
q1= np.percentile(sepal_width,25)
q1

2.0

In [100]:
q3= np.percentile(sepal_width,75)
q3

3.0

In [101]:
IQR= q3-q1
IQR

1.0

In [102]:
lower_limit = q1-1.5*IQR
lower_limit

0.5

In [103]:
upper_limit= q3+1.5*IQR
upper_limit

4.5

In [104]:
print(sepal_width[sepal_width>upper_limit]) #no outliers

print(sepal_width[sepal_width<lower_limit])

[]
[]


### petal_length

In [72]:
petal_length = iris[1:,2:3]

In [73]:
petal_length= np.where(petal_length== -1,np.nan,petal_length)
petal_length

array([[ 1.4],
       [ 1.4],
       [ 1.3],
       [ 1.5],
       [ 1.4],
       [ 1.7],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ nan],
       [ 1.5],
       [ 1.6],
       [ 1.4],
       [ 1.1],
       [ 1.2],
       [ 1.5],
       [ 1.3],
       [ 1.4],
       [ 1.7],
       [ 1.5],
       [ 1.7],
       [ 1.5],
       [ 1. ],
       [ 1.7],
       [ 1.9],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.4],
       [ 1.6],
       [ 1.6],
       [ 1.5],
       [ 1.5],
       [ 1.4],
       [ 1.5],
       [ 1.2],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [ 1.5],
       [ 1.3],
       [13. ],
       [ 1.3],
       [ 1.6],
       [ 1.9],
       [ 1.4],
       [ 1.6],
       [ 1.4],
       [ 1.5],
       [ 1.4],
       [ 4.7],
       [ 4.5],
       [ 4.9],
       [ 4. ],
       [ 4.6],
       [ 4.5],
       [ 4.7],
       [ 3.3],
       [ 4.6],
       [ 3.9],
       [ 3.5],
       [ 4.2],
       [ 4. ],
       [ 4.7],
       [ 3.6],
       [ 4.4],
       [ 4

In [105]:
med= np.nanmedian(petal_length)
med

4.5

In [106]:
petal_length= np.where(np.isnan(petal_length),med,petal_length)  #replacing missing values with median

In [107]:
cond= (petal_length>4)|(petal_length<0)

In [109]:
petal_length= np.where(cond,med,petal_length).astype("int32") #Type conversion
petal_length                                                  # replacing outliers with median

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [4],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [3],
       [4],
       [3],
       [3],
       [4],
       [4],
       [4],
       [3],
       [4],
       [4],
       [4],
       [4],
       [3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [3],
       [4],
       [3],
       [3],
    

### petal_width

In [63]:
petal_width = iris[1:,3:]
petal_width

array([[2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [1.020e+01],
       [2.000e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [1.010e+01],
       [9.998e-02],
       [2.000e-01],
       [3.999e-01],
       [3.999e-01],
       [3.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [5.000e-01],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [2.000e-01],
       [1.102e+02],
       [2.000e-01],
       [2.000e-01],
       [3.999e-01],
       [9.998e-02],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [9.998e-02],
       [2.000e-01],
       [2.000e-01],
       [3.000e-01],
       [3.000e-01],
       [2.000e-01],
       [6.001e-01],
       [3.999e-01],
       [3.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],
       [2.000e-01],


In [65]:
med= np.nanmedian(petal_width)
med

1.5

In [69]:
cond= (petal_width>3)|(petal_width<0)

In [110]:
petal_width= np.where(cond,med,petal_width).astype("int32")   # type conversion
petal_width                                                   # replacing outliers with median

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [4],
       [4],
       [4],
       [1],
       [4],
       [4],
       [4],
       [1],
       [4],
       [1],
       [1],
       [4],
       [1],
       [4],
       [1],
       [4],
       [4],
       [4],
       [4],
       [1],
       [4],
       [1],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [1],
       [4],
       [1],
       [1],
    

In [118]:
cleaned_data= np.hstack([sepal_length,sepal_width,petal_length,petal_width])

In [119]:
np.savetxt("cleaned.txt",cleaned_data)

In [120]:
np.loadtxt("cleaned.txt")

array([[5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [1., 1., 1., 1.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 2., 1., 0.],
       [4., 3., 1., 1.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [1., 1., 1., 1.],
       [4., 3., 1., 0.],
       [5., 4., 1., 0.],
       [5., 4., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [1., 1., 1., 1.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 4., 1., 0.],
       [5., 4., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
       [5., 3., 1., 0.],
       [4., 3., 1., 0.],
       [4., 3., 1., 0.],
       [5., 3., 1., 0.],
