### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]


1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

In [1]:
import numpy as np

In [27]:
student_marks= np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
student_marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [61]:
missing_values = np.sum(np.isnan(student_marks))

print("number of missing values are:",missing_values)

number of missing values are: 4


In [70]:
outliers = np.sum((student_marks>100) | (student_marks<0))

print("number of outliers are :",outliers)

number of outliers are : 3


In [62]:
a = np.where(np.isnan(student_marks),87,student_marks)  #replacing missing values with 87
a

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [64]:
cond= (a>100) | (a<0)   #let's assume that the marks less than 0 and greater than 100 will be outliers

In [65]:
new_marks = np.where(cond,45,a)   #replacing outlier with 45
new_marks

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.])

In [66]:
np.mean(new_marks)

56.96551724137931

In [67]:
len(new_marks[new_marks<60])

18

In [68]:
np.max(new_marks)

97.0

In [69]:
np.array(new_marks).astype("float32")

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

### Solving Linear Equations
    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12

    
Solve the system of equations using NumPy's linalg.solve function.


In [73]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b = np.array([10,5,12])

np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
 
    
Solve the system of equations using NumPy's linalg.solve function.


In [130]:
c= np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
d= np.array([8,1,7,3])

np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


In [131]:
e = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
f = np.array([10,-3,4])

np.linalg.solve(e,f)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where()

1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

In [119]:
A= np.random.randint(1,100,10)
A

array([33,  6, 83, 52, 25, 81, 81, 33, 21,  9])

In [120]:
indices= np.where(A>50)

In [121]:
B= A[indices]
M= np.mean(B)

In [122]:
print("A is :",A)
print("B is :",B)
print("mean of B is :",M)

A is : [33  6 83 52 25 81 81 33 21  9]
B is : [83 52 81 81]
mean of B is : 74.25


### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [124]:
C= np.random.randint(-10,10,size=(4,4))
C

array([[ 0,  8,  8,  2],
       [ 8,  0, -5,  3],
       [-5,  9, -7,  7],
       [-6,  5, -5,  3]])

In [127]:
B= np.where(C<=0,0,C)

In [129]:
B

array([[0, 8, 8, 2],
       [8, 0, 0, 3],
       [0, 9, 0, 7],
       [0, 5, 0, 3]])