**Creation of ndarray**
1. Write python code to create 3d array in different ways with 15 elements.

2. Array Creation:

     a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
     
     b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
     
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**1. Write python code to create 3d array in different ways with 15 elements.**

In [1]:
import numpy as np

In [19]:
arr1= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin=3) #creating using ndmin
print(arr1)
arr1.ndim

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]]


3

In [20]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(1,3,5) #creating using reshape()
print(arr2)
arr2.ndim

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


3

In [24]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(1,1,15)
print(arr2)
arr2.ndim

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]]


3

In [13]:
arr3= np.array([[[1,2,3,4,5,6,7,8,9]]]) #creating using []
print(arr3)
arr3.ndim

[[[1 2 3 4 5 6 7 8 9]]]


3

**2. Array Creation:**

a. Create a 4D NumPy array containing the first 12 positive integers as arr1.

In [230]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
print(arr1)
arr1.ndim

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


4

b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

In [34]:
import random 
array1 = np.random.randint(0,2,20)
array1

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0])

**3. Find all attributes of array1 and array2**

In [260]:
arr1   #attributes of array1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [52]:
arr1.dtype

dtype('int32')

In [53]:
arr1.size

12

In [54]:
arr1.nbytes

48

In [55]:
arr1.itemsize

4

In [56]:
arr1.ndim

4

In [45]:
array2 = np.linspace(1,13,20)  #attributes of array2
array2

array([ 1.        ,  1.63157895,  2.26315789,  2.89473684,  3.52631579,
        4.15789474,  4.78947368,  5.42105263,  6.05263158,  6.68421053,
        7.31578947,  7.94736842,  8.57894737,  9.21052632,  9.84210526,
       10.47368421, 11.10526316, 11.73684211, 12.36842105, 13.        ])

In [46]:
array2.dtype

dtype('float64')

In [47]:
array2.size

20

In [48]:
array2.nbytes

160

In [49]:
array2.ndim

1

In [50]:
array2.itemsize

8

**4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.**

#### For arr1

In [261]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

Describe:
    
* Rows X columns = 4rows X 3columns
* datatype = int32
* outliers = 0
* missing values =0

**Measure of central tendency**

In [262]:
arr1.mean() #mean

6.5

In [263]:
np.median(arr1) #median

6.5

**Measure of spread**

In [264]:
Range= arr1.max()-arr1.min()
Range

11

In [265]:
Range = np.max(arr1)-np.min(arr1)
Range

11

In [266]:
np.var(arr1)

11.916666666666666

In [267]:
np.std(arr1)

3.452052529534663

**IQR**

In [268]:
Q1= np.percentile(arr1,25)
Q1

3.75

In [269]:
Q2= np.percentile(arr1,50)
Q2

6.5

In [73]:
Q3= np.percentile(arr1,75)
Q3

9.25

In [75]:
IQR = Q3-Q1
IQR

5.5

In [77]:
lower = Q1-(1.5*IQR)
lower

-4.5

In [78]:
upper = Q3+(1.5*IQR)
upper

17.5

In [84]:
print(arr1[arr1>upper])      #Outlier = no outliers

print(arr1[arr1<lower])

[]
[]


#### For array2

In [151]:
array2 = np.linspace(1,13,20)
array2

array([ 1.        ,  1.63157895,  2.26315789,  2.89473684,  3.52631579,
        4.15789474,  4.78947368,  5.42105263,  6.05263158,  6.68421053,
        7.31578947,  7.94736842,  8.57894737,  9.21052632,  9.84210526,
       10.47368421, 11.10526316, 11.73684211, 12.36842105, 13.        ])

**Describe**

* rows x columns = 4rows X 5column
* datatype = float64
* missing values = 0
* outliers= 0

**Measure of central tendency**

In [87]:
#Mean

array2.mean()

7.0

In [88]:
#Meadian

np.median(array2)

7.0

**Measure of spread**

In [89]:
#range

Range = max(array2)- min(array2)
Range

12.0

In [90]:
#variance

np.var(array2)

13.263157894736839

In [91]:
#standard deviation

np.std(array2)

3.6418618720013036

**IQR**

In [93]:
Q1 = np.percentile(array2,25)
Q1

4.0

In [94]:
Q2 = np.percentile(array2,50)
Q2

7.0

In [95]:
Q3 = np.percentile(array2,75)
Q3

10.0

In [96]:
IQR = Q3-Q1
IQR

6.0

In [97]:
lower_limits = Q1- (1.5 * IQR)
lower_limits

-5.0

In [98]:
upper_limits = Q3 + (1.5 * IQR)
upper_limits

19.0

In [99]:
print(array2[array2>upper])      #Outlier = no outliers

print(array2[array2<lower])

[]
[]


**Array Slicing and Indexing:**

a. Creating Arrays:
   
   - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
   - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
b.Basic Indexing:
 
   - Print the element at index 3 of  arr1.
   - Print the element at row 2, column 1 of  arr2

c. Array Slicing:
   
   - Print the first five elements of arr1.
   - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
   - Print every second element starting from index 1 up to index 7 of arr1.


In [106]:
arr1= np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr2=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [101]:
arr1[2]

26

In [108]:
arr2[1][1]

4

In [112]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [137]:
arr2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [139]:
arr1[1:7:2]

array([11, 73, 51])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
   
   - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
   - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.

In [147]:
int_array= np.array([1, 2, 3, 4, 5],dtype= "int16")
float_array= np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(int_array.dtype)
print(float_array.dtype)

int16
float64


b. Data Type Conversion:
   
   - Convert the `float_array` to an array with data type `int32`. Print the result.
   - Convert the `int_array` to an array with data type `float32`. Print the result.

In [145]:
a= np.array(int_array,dtype="int32")
a.dtype

dtype('int32')

In [149]:
b= np.array(float_array,dtype="float32")
b.dtype

dtype('float32')

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).


In [154]:
rand_integers= np.random.randint(0,101,10)
rand_integers

array([84, 45, 18, 47, 17, 36, 21,  6, 53, 48])

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

In [156]:
rand_uniform= np.random.uniform(-1,1,5)
rand_uniform

array([ 0.86487611, -0.31051501, -0.59137934, -0.99224823, -0.54941451])

3. Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix.

In [166]:
rand_matrix = np.random.randint(50,100,16).reshape(4,4)
rand_matrix

array([[98, 60, 96, 90],
       [96, 63, 94, 52],
       [68, 63, 50, 56],
       [68, 67, 82, 63]])

**4.	Apply descriptive statistics for rand_matrix.**

**measure of central tendency**

In [168]:
rand_matrix.mean()    #mean

72.875

In [170]:
np.median(rand_matrix)   #median

67.5

**Measure of spread**

In [171]:
Range = np.max(rand_matrix)-np.min(rand_matrix)
Range

48

In [172]:
np.var(rand_matrix)   #variance

269.234375

In [173]:
np.std(rand_matrix)    #standard deviation

16.4083629591742

#### IQR

In [176]:
Q1= np.percentile(rand_matrix,25)
Q1

62.25

In [177]:
Q2= np.percentile(rand_matrix,50)
Q2

67.5

In [178]:
Q3= np.percentile(rand_matrix,75)
Q3

91.0

In [179]:
IQR= Q3-Q1
IQR

28.75

In [181]:
Lower_limit = Q1-(1.5*IQR)
Lower_limit

19.125

In [183]:
Upper_limit= Q3+(1.5*IQR)
Upper_limit

134.125

In [187]:
print(rand_matrix[rand_matrix > Upper_limit])  #Outliers = No outliers
print(rand_matrix[rand_matrix < Lower_limit])

[]
[]


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:

1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?

In [252]:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [253]:
sal = np.array(Salaries)
sal

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [254]:
len(sal[sal<50000])

5

In [255]:
np.median(sal)

61699.5

In [256]:
Range= max(sal)- min(sal)
Range

3082388

In [275]:
Q3= np.percentile(sal,75)
m = np.mean(sal)
print(Q3)
print(m)

84496.5
166169.16666666666


In [278]:
sal= sal[(sal > m) & (sal <=Q3)]
sal

array([], dtype=int32)

In [249]:
Q1= np.percentile(sal,25)
len(sal[sal<Q1])

8